### ISSUE TITLE
Converting into a web api with Django and Celery. 

### ISSUE THREAD

**Issue by Sayrikey1** [trancethehuman/entities-extraction-web-scraper#1]
I've been trying to convert this code into a callable api through a Django application, and perform the scrapping through celery.

But I kept on getting the coroutine error. I was able to deal with the error using this https://stackoverflow.com/questions/39815771/how-to-combine-celery-with-asyncio

But the problem now is, the celery task just fires and ends without performing any scrapping job.

What can I do to solve this?

**Comment by trancethehuman** [comment]
Do you have the code snippet for it?

**Comment by Sayrikey1** [comment]
Thank you. 

I've been able to solve the problem, using pythons `async_to_sync` function from `asgiref.sync` library.

But I'm currently facing another error from OpenAI

```
Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')).

```

Which was working fine previously.

**Comment by trancethehuman** [comment]
That's interesting. I got the same error running LangServe recently. @hwchase didn't get the same error though. I'm assuming there's something funky from OpenAI at the moment.

<img width="655" alt="Screenshot 2023-10-17 at 1 09 01 PM" src="https://github.com/trancethehuman/entities-extraction-web-scraper/assets/16231195/911e71a7-9491-48a7-b165-be4897bd99e4">

**Comment by Sayrikey1** [comment]
> That's interesting. I got the same error running LangServe recently. @hwchase didn't get the same error though. I'm assuming there's something funky from OpenAI at the moment.
> 
> <img width="655" alt="Screenshot 2023-10-17 at 1 09 01 PM" src="https://github.com/trancethehuman/entities-extraction-web-scraper/assets/16231195/911e71a7-9491-48a7-b165-be4897bd99e4">
> 
> 

Oh.. Hopefully it gets resolved soon.
